### ISSUE TITLE
after fresh clone transport test fails with mvn clean install

### ISSUE THREAD

**Issue by ronenhamias** [scalecube/scalecube#103]
@antonkharenko @artem-v 
clone the repository and run mvn clean install
I 1103-1731:54,574 i.s.t.TransportTest ####### testConnectorSendOrder1Thread : iteration = 8 [main]
I 1103-1731:55,597 i.s.t.Transport Bound to: 10.159.4.229:4802 [sc-boss-91-1]
I 1103-1731:55,605 i.s.t.Transport Connected from 10.159.4.229:4802 to 10.159.4.229:4801: [id: 0x4fcf6bc0, L:/10.159.4.229:53019 - R:/10.159.4.229:4801] [sc-io-92-1]
I 1103-1731:56,194 i.s.t.TransportTest ####### testConnectorSendOrder1Thread : iteration = 9 [main]
I 1103-1731:57,208 i.s.t.Transport Bound to: 10.159.4.229:4802 [sc-boss-93-1]
I 1103-1731:57,214 i.s.t.Transport Connected from 10.159.4.229:4802 to 10.159.4.229:4801: [id: 0xdb1ea334, L:/10.159.4.229:53042 - R:/10.159.4.229:4801] [sc-io-94-1]
I 1103-1731:58,086 i.s.t.BaseTest ********** Test finished: TransportTest.testConnectorSendOrder1Thread ********** [main]
I 1103-1731:58,087 i.s.t.BaseTest ********** Test started: TransportTest.testPingPongClientTFListenAndServerTFListen ********** [main]
I 1103-1731:59,104 i.s.t.Transport Bound to: 10.159.4.229:4801 [sc-boss-95-1]
I 1103-1732:00,121 i.s.t.Transport Bound to: 10.159.4.229:4802 [sc-boss-97-1]
I 1103-1732:00,125 i.s.t.Transport Connected from 10.159.4.229:4801 to 10.159.4.229:4802: [id: 0xf454f69e, L:/10.159.4.229:53086 - R:/10.159.4.229:4802] [sc-io-96-2]
I 1103-1732:00,130 i.s.t.Transport Connected from 10.159.4.229:4802 to 10.159.4.229:4801: [id: 0xb27168bd, L:/10.159.4.229:53087 - R:/10.159.4.229:4801] [sc-io-98-2]
I 1103-1732:00,138 i.s.t.BaseTest ********** Test finished: TransportTest.testPingPongClientTFListenAndServerTFListen ********** [main]
I 1103-1732:00,139 i.s.t.BaseTest ********** Test started: TransportTest.testInvalidListenAddress ********** [main]
I 1103-1732:00,154 i.s.t.BaseTest ********** Test finished: TransportTest.testInvalidListenAddress ********** [main]
I 1103-1732:00,155 i.s.t.BaseTest ********** Test started: TransportTest.testInvalidListenConfig ********** [main]
I 1103-1732:00,164 i.s.t.BaseTest ********** Test finished: TransportTest.testInvalidListenConfig ********** [main]
I 1103-1732:00,170 i.s.t.BaseTest ********** Test started: TransportTest.testUnresolvedHostConnection ********** [main]
I 1103-1732:01,182 i.s.t.Transport Bound to: 10.159.4.229:4801 [sc-boss-103-1]
W 1103-1732:04,046 i.s.t.Transport Failed to connect from 10.159.4.229:4801 to wronghost:49255 [sc-io-104-1]
I 1103-1732:04,051 i.s.t.BaseTest ********** Test finished: TransportTest.testUnresolvedHostConnection ********** [main]
Tests run: 15, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 88.908 sec <<< FAILURE! - in io.scalecube.transport.TransportTest
testBlockAndUnblockTraffic(io.scalecube.transport.TransportTest)  Time elapsed: 4.627 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<2>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at io.scalecube.transport.TransportTest.testBlockAndUnblockTraffic(TransportTest.java:423)

testNetworkSettings(io.scalecube.transport.TransportTest)  Time elapsed: 3.098 sec  <<< FAILURE!
java.lang.AssertionError: expectedMax=550, actual size=1000
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.scalecube.transport.TransportTest.testNetworkSettings(TransportTest.java:276)

**Comment by antonkharenko** [comment]
can't reproduce
