### ISSUE TITLE
multiple seed nodes

### ISSUE THREAD

**Issue by rmchale** [scalecube/scalecube#175]
How would this work multiple seed nodes?  I want to start a few seed nodes for redundancy, but I am unsure how they would talk to each other.

https://github.com/scalecube/scalecube/blob/master/cluster/src/test/java/io/scalecube/cluster/ClusterTest.java

I am picturing 
JavaApp1(seed node)
```
   Cluster.joinWait()
```
JavaApp2(seed node)
```
   Cluster.joinWait()
```

**Comment by antonkharenko** [comment]
You may provide multiple seed node addresses of joinAwait call or use ClusterConfig class (see following example https://github.com/scalecube/scalecube/blob/master/examples/src/main/java/io/scalecube/examples/ClusterJoinExamples.java). 

Also when you start seed nodes itself you can also provide to the addresses of other seed nodes. General idea is that you start seed nodes on some well-known addresses.

**Comment by ronenhamias** [comment]
I was thinking that seed nodes might be registered in DNS like solutios so when connecting to the cluster you always connect to "seed" service 

for example you register seed nodes at the docker swarm discovery service and it will give you ip so you can transparently connect to the cluster.

**Comment by antonkharenko** [comment]
@ronenhamias I think you can do it right now, without any code changes at scalecube project. Just provide as seed member DNS hostname or is there any issues with that?

**Comment by ronenhamias** [comment]
when you are using docker swarm services are registered under DNS name. and swarm manages their location. if a service goes up or down it might appear in a new location with new IP.

when ServiceA calls ServiceB swarm controls the routing using DNS names.

so in case you want to control the routing and selection of services DNS routing is very limited approach as its only round rubin endpint selection.

the solution i was thinking of was that only have seed nodes under the service discovery while joining to the cluster and services will communicate using IP across docker nodes.

one issue is that when cluster starts it might have dynamic port allocation and docker expose is for specific ports and not range of ports.
