### ISSUE TITLE
Website enhacement

### ISSUE THREAD

**Issue by kshchepanovskyi** [scalecube/scalecube#18]
Why don't you use [jekyll](http://jekyllrb.com/) or other site generator?

Take a look at [protostuff maven plugin page](http://www.protostuff.io/documentation/maven-plugin/). It is generated from this nice [markdown source file](https://github.com/protostuff/protostuff.github.io/blob/master/documentation/maven-plugin.md).

**Comment by antonkharenko** [comment]
@kshchepanovskyi Sounds interesting, need to check since just wasn't aware regards this project.

**Comment by ronenhamias** [comment]
colosing this issue as we improved the website
http://scalecube.io/
