### ISSUE TITLE
Scalecube + Docker

### ISSUE THREAD

**Issue by mbarker** [scalecube/scalecube#197]
I might be going about this wrong, but I'm having some issues with running scale cube within docker. 

So let's say I have 2 docker hosts: `api1` and `api2`. I have a seed service which just initializes the `Cluster`, I'm setting the `port` and using `syncGroup`, and passing in the list of `seeds` (pretty standard stuff). Bake the service into a docker container and run it on `api1` and `api2` passing the seeds of `api1:20000,api2:20000`. 

Each service starts up ok, and then I get a whole bunch of warnings like:
```
Failed to connect from 172.17.0.5:20000 to 172.17.0.8:20000
```

So I wired up some endpoints that spit out some info around the `Cluster` (members). 

The first instance of the service will only have itself as a member, the second instance will have both instances as a member of the cluster (but it still warns every second failing to connect).

I noticed that the ips are all `172.17.x.x` which makes sense, that's what `localhost` resolves to for each of the docker containers. I figured that was the problem (they aren't on the same network), so I saw I could set what address/interface gossip should bind to. I tried several combinations without luck (using hostname or local ip of the docker hosts throws an exception, failing to bind within the docker container because it's not part of the network interfaces). Without bridging the docker networks between docker hosts, is there a way I can set this up to work between docker hosts, or from a docker host to a non docker host within the same network?

**Comment by ronenhamias** [comment]
Hello and thanks for your comment.

First:
did you have a look on the microservices project that runs the scalecube as dockers?
https://github.com/scalecube/microservices

can you describe little more about the topology you have is it on same host or across different hosts and docker engines?

one thing that comes to my mind is to create a network between hosts using SWARM maybe?

we can discuss it on 
https://gitter.im/scalecube/Lobby

**Comment by mbarker** [comment]
@ronenhamias I know we walked through a few options in our discussion, but this is sort of what I had in mind (to avoid changing our deployment strategy, or build a custom network across docker hosts).
#198

**Comment by antonkharenko** [comment]
@mbarker It seems to me that more ordinary approach would be to create network using [docker network](https://docs.docker.com/engine/reference/commandline/network/) commands and then start docker containers on that network. Also, we have created separate small tool to do it even from Java code at https://github.com/scalecube/docker-utils, check readme for some examples on this specific part. 

Coming back to your pull request, I am just try to figure out what exactly you are setting into hostAddress to make it work (btw, did you check if this change solved your issue?). Do you start a several docker containers on same machine and then map them to some address/port so they can connect to each other? I think in such case you need not only a host address, but also host port as well - isn't it? And also if this is the case I would probably call change the names in pull request in the following way.

**Comment by mbarker** [comment]
Closing with #203
