### ISSUE TITLE
Moving to Reactor project by Spring

### ISSUE THREAD

**Issue by stavalfi** [scalecube/scalecube#293]
From https://github.com/ReactiveX/RxJava:

> Version 1.x
The 1.x version is end-of-life as of March 31, 2018. No further development, support, maintenance, PRs, and updates will happen. The Javadoc of the very last version, 1.3.8, will remain accessible.

Are there any plans to move to RxJava 2 or better - **Reactor project by spring?**

Personally, from a first look only, this repository looks awesome and it's **reactive** (:D) but the cost of learning a depreciated library is high. 

I'm sure this issue requires a __full-refactoring__ but `Java9` support for [reactive-streams specification](http://www.reactive-streams.org/) and `Spring 5` is the best reason to do it and do it fast.

Please fill free to correct me If I'm wrong about something. My knowledge about your library ends with 10 minutes of reading and a big drive to getting started :)

**Comment by OlegDokuka** [comment]
Wow, hey buddy. They are moving to Reactor actually :smile:

**Comment by stavalfi** [comment]
Hi man! good to know you are here also! Thanks for the information :D

**Comment by ronenhamias** [comment]
@stavalfi 
please take a look here:
https://github.com/scalecube/scalecube-services

this version will be merged at this repository in future.
