### ISSUE TITLE
Define Transport and Cluster thread model

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube#44]
**Q1:**  next code in ``Transport.start()``:
```java
incomingMessagesSubject.subscribeOn(Schedulers.from(eventExecutor)); // define that we making smart subscribe
```
Why?  Nice reference: http://www.grahamlea.com/2014/07/rxjava-threading-examples

**Q3:** in the ``TransportPipelineFactory.resetDueHandshak()`` we have: 
```java
pipeline.addBefore(transportSpi.getEventExecutor(), "exceptionHandler", "messageReceiver", messageHandler);
```
Why? Can't we allow to execute business logic right in netty thread? 

**Q2:**  we expose ``ITransportSpi.getEventExecutor()``. Primary clients of it are: 
```java
clusterMembership =
        new ClusterMembership(localTransportEndpoint, Schedulers.from(transport.getEventExecutor()));
```
```java
failureDetector =
        new FailureDetector(localTransportEndpoint, Schedulers.from(transport.getEventExecutor()));
```
Is it safe to expose entire ``eventExecutor``? Can't we expose just concrete stuff (which ``Scheduler`` is)? 

**Q3:** gossip causing creation of redudant thread pools:
In ``ClusterMembershipBuilder``:
```java
gossipProtocol = new GossipProtocol(transportEndpoint, Executors.newSingleThreadScheduledExecutor());
```
Weird constructor: 
```java
  public GossipProtocol(TransportEndpoint localEndpoint) {
    this.localEndpoint = localEndpoint;
    this.executor = createDedicatedScheduledExecutor();
  }
```
Let' s not allow gossip (and other objects) create their own executors, instead, make it use of transport's thread pool (which is in fact netty thread pool).

**Comment by antonkharenko** [comment]
Solved at PR: https://github.com/scalecube/scalecube/pull/88
