### ISSUE TITLE
Implement graceful shutdown of cluster member

### ISSUE THREAD

**Issue by antonkharenko** [scalecube/scalecube#97]
When member is leaving cluster via `Cluster.shutdown` we can notify members about shutdown so they can remove member immediately from membership table without detecting it failed and waiting required timeouts. Consider either to do it via regular membership gossips to spread status `DEAD` or use dedicated message type for this case.

**Comment by ronenhamias** [comment]
i suggest there will be a message LEFT indicating this node has LEFT the cluster as opposed to DEAD.

so there will be an ability to deal with this diffrentlly

for example in services we want to know that the cluster is leaving so stop route messages to it but the service transport of the node still serve requests.

so there might be some time between LEFT and DIED

LEFT means the node is still running but wanted to be excluded from membership
DIED means its totally dead and not available for any reasons.
